version: '3.2'

volumes:
  jenkins:

services:
  grafana:
    image: grafana/grafana
    depends_on:
        - prometheus
    ports:
      - 3000:3000
      
  jenkins-ansible:
    build: 
        context: ./     
    ports: 
        - 888:8080     
    volumes: 
        - jenkins:/var/jenkins_home       
    depends_on:
      - prometheus 

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml    
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - elliottsmetrics-cadvisor
    
  elliottsmetrics-cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: elliottsmetrics-cadvisor #cadvisor 
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    # - /var/run:/var/run:ro  #volume mappping for linux 
    - /var/run/docker.sock:/var/run/docker.sock:rw  #volume mappping for mac
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  #   depends_on:
  #   - redis
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #   - 6379:6379